### ISSUE TITLE
Better error catch 

### ISSUE THREAD

**Issue by elenoir** [SimplyUb/MultiChainJavaAPI#15]
When credentials are wrong, we received : 

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

We should check the status code and return more comprehensible exception through the API.

**Comment by erotundo** [comment]
Hi!

i got the same error, do you solved?

Thanks!

**Comment by erotundo** [comment]
@elenoir Hi again you can add this code in file QueryBuilderCommon of multichain/command/builders

if(response.getStatusLine().getStatusCode() != 200){
			throw new MultichainException("code :" + response.getStatusLine().getStatusCode(),
					"message : " + response.getStatusLine().getReasonPhrase());
		}
