### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by dave1981** [SimplyUb/MultiChainJavaAPI#17]
Can I connect to my multichain if my local host where java code is used is behind a proxy?

**Comment by ssls18years** [comment]
Yes, i meet the problem to, I debug my code in my notebook, but i can't connect to my multichain in server node. any idea pls...

**Comment by SimplyUb** [comment]
Hi,
Do you know the rules of your firewall ? And can you change them ?

First of all, when you create your BlockChain, you can change the value of "default-rpc-port" in the parameters. If there's no web server on the computer having the BlockChain, you can define the port 8080. Often the port 8080 is ok to pass accross firewall.
But, maybe the firewall has a rule on IP address. In this case, you have to allow your IP address.

And at the end, you have to find the external IP address of your RPC server. A firewall is a gate between internal network and external network, and internal network uses its own IP addresses and shows different addresses for the external network (often only one address is shown for the outside, even a few addresses are used in the internal network).
The firewall has redirection rules, you have to define a rule to send network request to the good internal IP address.

Does this information help you ?
If I'm already outside of your problem, can you give me more details to understand where is the problem ?

**Comment by ssls18years** [comment]
i solved the problem.

you shoud config in multichain.conf

rpcallowip=0.0.0.0/0
