### ISSUE TITLE
can't find api "createkeypairs"

### ISSUE THREAD

**Issue by ssls18years** [SimplyUb/MultiChainJavaAPI#18]
I want to create address and it's private key can't store in wallet(node), but i can't find it in javaapi.
help me pls.

**Comment by SimplyUb** [comment]
Hi,
**_CreateKeyPairs was added with version 0.4.3._**
Can you say me if it's all you need ?
It's not function I usually use then I don't know what's is needed.

Why do you need CreateKeyPairs to create an address ? Why don't you simply use CreateAddress ?
