### ISSUE TITLE
Send data to MultiChain server

### ISSUE THREAD

**Issue by erotundo** [SimplyUb/MultiChainJavaAPI#19]
Hi!

I'm new in this so my question if this api has the option to send transactions and get the transaction identifier

Regards

ER

**Comment by SimplyUb** [comment]
Hi,

When you look up at one command which allows to send, you can see :
`
Result: "transactionid" (string) The transaction id.
[...]
public String sendFromAddress [...]
`

The return of the command is the transaction Id. Is it this identifier you want to get ?

Regards,
Hubert

**Comment by erotundo** [comment]
Ok, so in this case with this return i can get this specific transaction using the rpc api right?

Regards,
Eduardo Rotundo

**Comment by SimplyUb** [comment]
Eduardo,

with the returned transaction id, you can use a command like :
`public Transaction getTransaction(String txid)`
and you'll receive all the information abotu the transaction (other command allow to have more information).

All the command I gave are in the API in class : WalletTransactionCommand in package multichain.command.

Regards,
Hubert

**Comment by erotundo** [comment]
Perfect!!

thanks for your quickly response :)

Regards,
Eduardo
