### ISSUE TITLE
Send encrypted data

### ISSUE THREAD

**Issue by erotundo** [SimplyUb/MultiChainJavaAPI#20]
Hi!

It's me again here. Now i try to find the way to do publish with encryption. i try to create my encryption process and send it to Multichain server, but the data don't appear into the MultiChain server. After reading the develop section in MultiChain the process to send encrypted data it's different and need pass to publish command the key with the data (previously you need to configure your server to use encrypted data) but the command into the api don't have this option (i don't know if this it's located in other place of this library Multi Chain Java Api)

It's coming into new version?

Regards
Eduardo

**Comment by elenoir** [comment]
Hi,

Could you explain a little bit what you want to do and which commands you have used?

Regards

**Comment by SimplyUb** [comment]
Hi,

I'm not sure to understand.

Talking about encryption, I know 2 parts : encryption of the wallet and encryption of data sent in transaction.

As I understand your question, you want to send data using a transaction.
Did you read this information in MultiChain Q&A :
https://www.multichain.com/qa/3473/how-to-encrypt-data-and-make-it-accessible-specific-address

Using the API, you should use the command :
`sendWithMetaData`
Data has to be in hex value mode (then convert string in hex).
You can send any data you want and there's no way to automatically encrypte data (in my knowledge).
Then, before to use the command, you have to encrypt data before to use it.

If you have to manage encryption keys, you can read too :
https://www.multichain.com/developers/stream-confidentiality/
(which is a nice tutorial ;) )

But, as Erik, I'm not sure to well understand your question.
Do I answer to it or am I completly at the side of it ?

Regards,
Hubert

**Comment by erotundo** [comment]
Hi @elenoir and @SimplyUb!

Sorry for answer so late.

My idea it's post a transaction into my multichain server but i want to send my stream with encrypted data. I saw if i only use the publish function the data converted to Hex don't maintain encrypted information and if you want to use decrypt when you try to read the stream you get a error because the byte[] don't have the real content.

The process of encryption it's not the problem because i have the code to create private and public key, but now i need to send to the server the encrypted information

Regards
Eduardo

**Comment by SimplyUb** [comment]
Hi Eduardo,

I'm not sure to understand.
The way I use it is :
With MMIS = My Message in String
1- Encrypt(MMIS, public key) => EncMMIS
2- hex(EncMMIS) => hexEncMMIS
3- publis(hexEncMMIS)

and then :
1- ReadPublication =>hexEncMMIS
2- hexToText(hexEncMMIS) => EncMMIS
3- Decrypt(EncMMIS, private key) => MMIS

I use it like that and it works !
What is the problem following this ?

Regards,
Hubert

**Comment by erotundo** [comment]
Hi @SimplyUb !

The problem it´s when i read the stream and i try to do the decrypt process i got a error "the length it's not valid". When i do the debug i see before to send the stream after encrypt i get a byte[] of 256 length.

when you read the transaction and do the reverse hex the length of byte[] it's 416

This is my code

`public static Key publicKey;
    public static Key privateKey;
    public static MultiChainCommand command;
    public static StreamCommand commandStream;
    public static String content = "this a example";
    public static String streamName = "exampleStream1";
    public static String key = "examplekey123123";
    public static void main(String[] args) {
	// write your code here

        //generateKeys();


        command = new MultiChainCommand("ip","port","user","key");
        try{
            commandStream = command.getStreamCommand();
            createTransaction();
            readTransaction();
        }catch (Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    public static String convertHexToString(String hex){

        StringBuilder sb = new StringBuilder();
        StringBuilder temp = new StringBuilder();

        //49204c6f7665204a617661 split into two characters 49, 20, 4c...
        for( int i=0; i<hex.length()-1; i+=2 ){

            //grab the hex in pairs
            String output = hex.substring(i, (i + 2));
            //convert hex to decimal
            int decimal = Integer.parseInt(output, 16);
            //convert the decimal to character
            sb.append((char)decimal);

            temp.append(decimal);
        }
        System.out.println("Decimal : " + temp.toString());

        return sb.toString();
    }

    static void createTransaction(){
        try {
            publicKey = getPrivateKey("C:\\apps\\public.key");
            byte[] message = encryptMessage(publicKey,content);
            System.out.println("Sin HEX -- " + new String(message));
            System.out.println("Con HEX -- " + new BigInteger(1,message).toString(16));
            //byte[] bytes = Hex.decodeHex(new BigInteger(1,message).toString(16).toCharArray());
            String dataContent = convertHexToString(new BigInteger(1,message).toString(16));
            System.out.println("Sin HEX -- " + dataContent);
            String result = commandStream.create(streamName,true);
            commandStream.publish(streamName,key,new BigInteger(1,message).toString(16));
            System.out.println(result);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    static void readTransaction(){
        List<Stream> resultList = null;
        try {
            resultList = commandStream.listStreams(streamName);
            resultList.get(0).getItems();
            List<StreamKeyItem> resultItemList = commandStream.listStreamKeyItems(streamName,key);
            StreamKeyItem result = resultItemList.get(0);

            String dataContent = result.getData();
            System.out.println("Con HEX -- " + dataContent);
            String hexString = dataContent;
            byte[] bytes = Hex.decodeHex(hexString.toCharArray());
            dataContent = new String(bytes, "UTF-8");
            System.out.println("Sin HEX -- " + dataContent);
            //dataContent =  new BigInteger(dataContent.getBytes()).toString();
            privateKey = getPrivateKey("C:\\apps\\private.key");
            Cipher decrypt=Cipher.getInstance("RSA");
            decrypt.init(Cipher.DECRYPT_MODE, privateKey);
            byte[] decryptedMessage=decrypt.doFinal(dataContent.getBytes());
        } catch (MultichainException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (BadPaddingException e) {
            e.printStackTrace();
        } catch (DecoderException e) {
            e.printStackTrace();
        } catch (InvalidKeyException e) {
            e.printStackTrace();
        } catch (NoSuchPaddingException e) {
            e.printStackTrace();
        } catch (IllegalBlockSizeException e) {
            e.printStackTrace();
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    static byte[] encryptMessage(Key publicKey,String msg) throws NoSuchPaddingException, NoSuchAlgorithmException, InvalidKeyException, BadPaddingException, IllegalBlockSizeException {
        // specify mode and padding instead of relying on defaults (use OAEP if available!)
        Cipher encrypt=Cipher.getInstance("RSA/ECB/PKCS1Padding");
// init with the *public key*!
        encrypt.init(Cipher.ENCRYPT_MODE, publicKey);
// encrypt with known character encoding, you should probably use hybrid cryptography instead
        byte[] encryptedMessage = encrypt.doFinal(msg.getBytes(StandardCharsets.UTF_8));
        return encryptedMessage;
    }

    public static Key getPrivateKey(String keyFileName)
            throws Exception {

        InputStream in = new FileInputStream(keyFileName);
        ObjectInputStream oin = new ObjectInputStream(new BufferedInputStream(
                in));
        try {
            BigInteger m = (BigInteger) oin.readObject();
            BigInteger e = (BigInteger) oin.readObject();
            KeyFactory fact = KeyFactory.getInstance("RSA");
            if (keyFileName.contains("public"))
                return fact.generatePublic(new RSAPublicKeySpec(m, e));
            else
                return fact.generatePrivate(new RSAPrivateKeySpec(m, e));
        } catch (Exception e) {
            throw new RuntimeException("Spurious serialisation error", e);
        } finally {
            oin.close();
            System.out.println("Closed reading file.");
        }
    }



    private static void generateKeys()
    {
        try {
            KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA");
            generator.initialize(2048);
            KeyPair keyPair = generator.generateKeyPair();
            publicKey = keyPair.getPublic();
            privateKey = keyPair.getPrivate();
            KeyFactory fact = KeyFactory.getInstance("RSA");
            RSAPublicKeySpec pub = fact.getKeySpec(publicKey,
                    RSAPublicKeySpec.class);
            RSAPrivateKeySpec priv = fact.getKeySpec(privateKey,
                    RSAPrivateKeySpec.class);

            saveToFile("C:\\apps\\public.key", pub.getModulus(),
                    pub.getPublicExponent());
            saveToFile("C:\\apps\\private.key", priv.getModulus(),
                    priv.getPrivateExponent());
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (InvalidKeySpecException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static void saveToFile(String fileName,
                                   BigInteger mod, BigInteger exp) throws IOException {
        ObjectOutputStream oout = new ObjectOutputStream(
                new BufferedOutputStream(new FileOutputStream(fileName)));
        try {
            oout.writeObject(mod);
            oout.writeObject(exp);
        } catch (Exception e) {
            throw new IOException("Unexpected error", e);
        } finally {
            oout.close();
        }
    }`

**Comment by elenoir** [comment]
Folks,

As @SimplyUb said, it's just about hexadecimal encoding.
In fact, everything you stored can be retrieved with the API ; it's up to you to implement the decoding and decryption phases in the good order. API is just about hexadecimal encoding/decoding.

**Comment by erotundo** [comment]
Hi @elenoir and @SimplyUb !

I solve the problem, effectively i had a problem in my decryption process to recover the hex transformation. Thanks for your cooperation

Best regards,

Eduardo
