### ISSUE TITLE
tcp link can't be closed.

### ISSUE THREAD

**Issue by ssls18years** [SimplyUb/MultiChainJavaAPI#23]
Hi, I found the tcp link was not closed when finished one api command. and the multichain will be frozen when tcp links exceed 4.

**Comment by elenoir** [comment]
indeed, the httpclient must be created and deleted after use

**Comment by s-ilnar** [comment]
How to fix this problem?

**Comment by SimplyUb** [comment]
I noticed the problem in implementing software in my side but never took the time to fix it.
it should be fixed by 4.6 (last commit).
Could you confirm it to be ?

**Comment by ssls18years** [comment]
Hi，SimplyUb, i try the new code, it's ok in my test environment, but it still be frozen in my production environment. i don't know the reason. i check the new code and found you use CloseableHttpResponse.

i roll back to the old version and still use HttpResponse and i add the "httpclient.close();", before every apicall, i reset the multiChainCommand. Although it looks stupid, it does solve the problem.
