### ISSUE TITLE
Many features do not work 

### ISSUE THREAD

**Issue by s-ilnar** [SimplyUb/MultiChainJavaAPI#24]
For example, 
1. the method of transferring assets from an address to an address does not work.
2. method is not working
```
String[] s = new String[]{"15B9xqugb9A6rVvAxb998c2jPx926S3VSY37UZ", "23B9xqugb9A6rVvAxb998c2jPx926S3VSY37UZ"};
MultiBalance list2 = getMultiChainCommand().getAddressCommand().getMultiBalances(s);
//error 500
```

**Comment by SimplyUb** [comment]
Hi,
bug fix in 4.6 (last commit).
Bug appeared with the usage of RPC server instead of system calls.

You talk about many features, can you list other ones ?
I correct those I find when I use them, but I'd lie in saying I use every feature.
