### ISSUE TITLE
Critical - Library becomes unresponsive after 4xx/5xx responses

### ISSUE THREAD

**Issue by kungfujoe** [SimplyUb/MultiChainJavaAPI#28]
There is a critical issue with the library such that if a couple (literally, I think...I think it's 2) requests are made to the RPC that result in 4xx or 5xx error codes, the library will become unresponsive because the Http pool fills up, because the response is not getting consumed.

I've got a pull request incoming to fix this.

**Comment by SimplyUb** [comment]
Thanks :)
