### ISSUE TITLE
ListBlocks

### ISSUE THREAD

**Issue by dave1981** [SimplyUb/MultiChainJavaAPI#33]
How can I list the most recent "x" blocks? Is there a function that acts like listblocks?

**Comment by SimplyUb** [comment]
Hi,

listblocks has been added by Leo (I just needed to manage merge request).

you can use it like that :
`		List<Block> resultlist = multiChainCommand.getBlockCommand().listBlocksList("10-50,100",false);
		System.out.println("resultlist size : " + resultlist.size());
		System.out.println("heights");
		for (int i =0; i<resultlist.size(); i++) {
			System.out.print(resultlist.get(i).getHeight()+"-");
		}
`
The code create a list with blocks 10 to 50 and with the block 100 too.
If you want to extract the last x blocks, you have to get the number of blocks (method getBlockCount) and then define your bounds.
