### ISSUE TITLE
 is it possible to establish a node using this api?

### ISSUE THREAD

**Issue by Topema** [SimplyUb/MultiChainJavaAPI#37]
Hello!

I am developing my final degree project using this API and I would like to know if it is possible to establish nodes using this api.

so, if a user is using a Dapp developed with this API, is it possible to allow the user run a node without making him download multichain?

thank you in advance for your help!!

**Comment by BertrandNOEL** [comment]
Hello,
No, this project makes RPC calls to a Multichain Server, it does not run anything by itself. You have to download and run Multichain by yourself

**Comment by SimplyUb** [comment]
Hi Topema,
As said by BertrandNoel, this project is, above all, done to call business MultiChain RPC Server functions.
Creation and starting a node need to be done by multichain-util and multichaind.

In fact, this project doesn't include "stop" function even it's included in RPC Server function list. In my personal opinion, if the project doesn't allow to start, it would be strange it allows to stop.
