### ISSUE TITLE
Permission codes do not match

### ISSUE THREAD

**Issue by luigima** [SimplyUb/MultiChainJavaAPI#38]
The permission codes seem to differ from the multichain ones.

https://github.com/SimplyUb/MultiChainJavaAPI/blob/e04f0b08a72b0bbfa14054ab3c2a4b4ea6313f16/src/main/java/multichain/command/builders/QueryBuilderGrant.java#L19-L26

Used by multichain:
https://www.multichain.com/developers/permissions-management/
connect=1, send=2, receive=4, issue=16, create=32, mine=256, admin=4096, activate=8192

**Comment by SimplyUb** [comment]
Hi,

that's certainly why execution commands begin by "formatPermissionsList" to get the right calling format.
Be sure that Grant command works even if the used values are not the same that MultiChain.
Next time, don't hesitate to test before to open issues ;-)
