### ISSUE TITLE
How to sign a raw transaction?

### ISSUE THREAD

**Issue by frazelli** [SimplyUb/MultiChainJavaAPI#43]
I got a hex string from `createrawsendfrom` and I need to sign it with a private key. Like described here in section "Send from the address" https://www.multichain.com/developers/external-key-management/

In multichain-cli I use this `signrawtransaction [paste-hex-blob] '[]' '["V..."]'`

For example:

> signrawtransaction '01000000011243edf5f1ed1d14272fae951232de25d26c1251f98299f2109924d1d7aae4ef0000000000ffffffff0200000000000000003776a91466750be1aeeaea5625ee4c2b35ba490b9b239f4e88ac1c73706b71d26c1251f98299f2101924d1d7aae4ef00ca8a3b000000007500000000000000003776a914c7b8b09a90bd696476da4d8330365f2bc42a906d88ac1c73706b71d26c1251f98299f2109924d1d7aae4ef0036dd26a441a7107500000000' '[]' '["VGFPVGY7f6JnG8LDhTwGTmTSeHCrWv23zYN2AoD8P2Htts1kDhH2pAMedE"]'

How can I use the same with the Java method `signRawTransaction(String hexString)`? Could you please give some examples?

**Comment by BertrandNOEL** [comment]
Hi, function `signRawTransaction` taking the optional private key as argument has not yet been developed
There should not be many changes to do to support that. If you develop it, please do a Merge Request and I'll review it
