### ISSUE TITLE
proof of work module?

### ISSUE THREAD

**Issue by Jovonni** [SimplyUb/MultiChainJavaAPI#5]
How is the proof of work being done in this?

**Comment by jagrutkosti** [comment]
MultiChainJavaAPI is only a wrapper for the API commands of [Multichain](https://www.multichain.com/developers/json-rpc-api/). This API itself does not implement any mining algorithm. 

But to answer your question briefly, Multichain's proof of work is same as Bitcoin with reduced difficulty and no requirements for specific chipset. To know more, I would suggest you to read the [Multichain White Paper](https://www.multichain.com/white-paper/).

**Comment by Jovonni** [comment]
Thanks for the link, reading
